

route_1:
    path:     /demo/{name}
    defaults: { _controller: 'Src\Controllers\DemoController::indexAction' }

secured_route_1:
    path:     /secured1
    defaults: { _controller: 'Src\Controllers\DemoController::secured1Action' }

secured_route_2:
    path:     /secured2
    defaults: { _controller: 'Src\Controllers\DemoController::secured2Action' }


#SECURITY

security_register:
    path:     /register
    defaults: { _controller: 'App\Lib\Security\SecurityController::registerAction' }
security_login:
    path:     /login
    defaults: { _controller: 'App\Lib\Security\SecurityController::loginAction' }
security_logout:
    path:     /logout
    defaults: { _controller: 'App\Lib\Security\SecurityController::logoutAction' }