firewall:
    login_route: security_login
    pattern:
        path: ^\/admin
        role: ROLE_ADMIN
    routes:
        secured_route_1: ROLE_USER
        secured_route_2: ROLE_ADMIN

providers:
    keys:
        provider_key: my_security_str
        crypt_key: azert45678fdsc23qsds
    in_memory:
        users:
            admin:
                password: 545cd6s1c2ds3d
                roles: [ROLE_SUPER_ADMIN]

roles:
    hierarchy:
        ROLE_SUPER_ADMIN: [ROLE_ADMIN,ROLE_USER]
        ROLE_ADMIN: [ROLE_USER]

encoders:
    Symfony\Component\Security\Core\User\User: plaintext
    Src\Entities\User: sha512