firewall:
    routes:
        secured_route_1: ROLE_USER
        secured_route_2: ROLE_ADMIN
    pattern:
        /admin: ROLE_ADMIN

providers:
    in_memory:
        provider_key: my_security_str
        users:
            stef:
                password: password
                roles: [ROLE_USER]
            admin:
                password: b109f3bbbc244eb82441917ed06d618b9008dd09b3befd1b5e07394c706a8bb980b1d7785e5976ec049b46df5f1326af5a2ea6d103fd07c95385ffab0cacbc86
                roles: [ROLE_ADMIN]

roles:
    hierarchy:
        ROLE_SUPER_ADMIN: [ROLE_ADMIN,ROLE_USER]
        ROLE_ADMIN: [ROLE_USER]

encoders:
    Symfony\Component\Security\Core\User\User: sha512 #plaintext
    Src\Entities\User: plaintext