services:
#    SERVICE DE L'APPLICATION
    profiler:
        class: App\Lib\Services\ProfilerService
        arguments: ["@parameters"]

    parameters:
        class: App\Lib\Services\ParametersService

    security.parameters:
        class: App\Lib\Services\SecurityParametersService

    router:
        class: App\Lib\Services\RouterService

    twig:
        class: App\Lib\Services\TwigService

    form.factory:
        class: App\Lib\Services\FormFactoryService

    doctrine:
        class: App\Lib\Services\DoctrineService
        arguments: ["@parameters"]

    session:
        class: Symfony\Component\HttpFoundation\Session\Session
        calls:
            - [ start ]

    encoder.factory:
        class: App\Lib\Services\EncoderFactoryService
        arguments: ["@security.parameters"]

    security:
        class: App\Lib\Services\SecurityService
        arguments: ["@security.parameters","@encoder.factory","@doctrine"]


