services:
#    SERVICE DE L'APPLICATION
    profiler:
        class: App\Lib\Services\ProfilerService
        arguments: ["@service_container"]

    parameters:
        class: App\Lib\Services\ParametersService

    security.parameters:
        class: App\Lib\Services\SecurityParametersService

    router:
        class: App\Lib\Services\RouterService

    form.factory:
        class: App\Lib\Services\FormFactoryService

    doctrine:
        class: App\Lib\Services\DoctrineService
        arguments: ["@parameters"]

    session:
        class: Symfony\Component\HttpFoundation\Session\Session
        calls:
            - [ start ]

    encoder.factory:
        class: App\Lib\Services\EncoderFactoryService
        arguments: ["@security.parameters"]

    security.context:
        class: App\Lib\Services\SecurityContextService
        arguments: ["@security.parameters","@encoder.factory","@doctrine"]

    helper:
        class: App\Lib\Services\HelperService
        arguments: ["@router"]

    twig:
        class: App\Lib\Services\TwigService

