

route_1:
    path:     /demo/{name}
    defaults: { _controller: 'Src\Controllers\DemoController::indexAction' }

secured_route_1:
    path:     /secured1
    defaults: { _controller: 'Src\Controllers\DemoController::secured1Action' }

secured_route_2:
    path:     /secured2
    defaults: { _controller: 'Src\Controllers\DemoController::secured2Action' }




#LOGIN

security_login:
    path:     /login
    defaults: { _controller: 'Src\Controllers\SecurityController::loginAction' }
security_logout:
    path:     /logout
    defaults: { _controller: 'Src\Controllers\SecurityController::logoutAction' }