

route_1:
    path:     /demo/{name}
    defaults: { _controller: 'Src\Controllers\DemoController::indexAction' }




#LOGIN

security_login:
    path:     /login
    defaults: { _controller: 'Src\Controllers\SecurityController::loginAction' }